SET SERVEROUTPUT ON;
SET TIMING ON;

CREATE TABLE EXAM_MARKS
(
    EXAM_MARK_ID INTEGER PRIMARY KEY,
    STUD_ID INTEGER REFERENCES STUDENT(STUD_ID),
    SUBJ_ID INTEGER REFERENCES SUBJECT(SUBJ_ID),
    MARK INTEGER,
    EXAM_DATE DATE,
    CONSTRAINT MARK_RANGE CHECK (MARK >= 2 AND MARK <= 5)
)

CREATE SEQUENCE EXAM_MARKS_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO EXAM_MARKS (EXAM_MARK_ID, STUD_ID, SUBJ_ID, MARK, EXAM_DATE)
VALUES (EXAM_MARKS_SEQ.NEXTVAL, 1, 1, 4, TO_DATE('2023-06-01', 'YYYY-MM-DD'));

INSERT INTO EXAM_MARKS (EXAM_MARK_ID, STUD_ID, SUBJ_ID, MARK, EXAM_DATE)
VALUES (EXAM_MARKS_SEQ.NEXTVAL, 2, 3, 5, TO_DATE('2023-06-15', 'YYYY-MM-DD'));

INSERT INTO EXAM_MARKS (EXAM_MARK_ID, STUD_ID, SUBJ_ID, MARK, EXAM_DATE)
VALUES (EXAM_MARKS_SEQ.NEXTVAL, 3, 2, 3, TO_DATE('2023-06-20', 'YYYY-MM-DD'));
